source 'https://github.com/CocoaPods/Specs.git'

target 'UIUserNotificationSettings-Extension', :exclusive => true do
  pod "UIUserNotificationSettings-Extension", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "UIUserNotificationSettings-Extension", :path => "../"
end
